# Generated by Django 5.0.6 on 2025-11-30 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recruitmentapp', '0002_delete_userregistration'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userregistration')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_recruitmentapp.jobposting')),
            ],
        ),
    ]
