# Generated by Django 5.0.6 on 2025-11-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recruitmentapp', '0003_jobposting_created_at_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(help_text='Meeting Link or Office Address', max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_recruitmentapp.jobapplication')),
            ],
        ),
    ]
