# Generated by Django 5.0.6 on 2025-11-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recruitmentapp', '0004_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
