# Generated by Django 5.0.6 on 2025-12-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_recruitmentapp', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
