# Generated by Django 5.0.6 on 2025-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Applicant', 'Applicant')], default='Applicant', max_length=20),
        ),
    ]
