# Generated by Django 5.0.6 on 2025-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userregistration_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='bio',
            field=models.TextField(blank=True, help_text='About User', null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma separated e.g. Python, Java', max_length=255, null=True),
        ),
    ]
